[server]
host = "0.0.0.0"
port = 8000

[nats]
url = "nats://nats:4222"
subject = "tasks"

[redis]
url = "redis://redis:6379"
db = 0

[quantum]
shots = 1024

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"